#!/bin/bash
function install()
{
    cd ~
    rm -rf myconf
    git clone git@github.com:sramanujan/myconf.git
    echo "Installation complete!"
}
function update()
{
    cd ~/myconf
    git pull origin master
    echo "Update complete!"
}
cd ~
if [ ! -d "myconf" ]; then 
    install; 
else
    if [ ! -d "myconf/.git" ]; then
        install;
    else
        update;
    fi
fi
exit
