#!/bin/bash
function install()
{
    cd ~
    rm -rf myconf
    git clone git@github.com:sramanujan/myconf.git
}
function update()
{
    cd ~/myconf
    git pull origin master
}
cd ~
if [ ! -d "myconf" ]; then 
    install; 
else
    if [ ! -d "myconf/.git" ]; then
        install;
    else
        update;
    fi
fi
echo "Pull complete"
~/myconf/scripts/post-install
echo "Install complete"
exit
